### ISSUE TITLE
http error in service.libreelec.settings

### ISSUE THREAD

**Issue by bylderup** [CoreELEC/CoreELEC#31]
although I did a fresh installation with coreelec there is this in kodi.log

12:22:07.318 T:3996119936   ERROR: ## LibreELEC Addon ## oe::load_url(http://releases.coreelec.org/releases.json) ## ERROR: (HTTPError())
12:22:07.320 T:3996119936   ERROR: Traceback (most recent call last):
                                              File "/data/CoreELEC/build.CoreELEC-S905.arm-9.0-devel/LibreELEC-settings-01a92b3/.install_pkg/usr/share/kodi/addons/service.libreelec.settings/oe.py", line 271, in load_url
                                              File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
                                              File "/usr/lib/python2.7/urllib2.py", line 435, in open
                                              File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
                                              File "/usr/lib/python2.7/urllib2.py", line 467, in error
                                              File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
                                              File "/usr/lib/python2.7/urllib2.py", line 654, in http_error_302
                                              File "/usr/lib/python2.7/urllib2.py", line 435, in open
                                              File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
                                              File "/usr/lib/python2.7/urllib2.py", line 473, in error
                                              File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
                                              File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
                                            HTTPError: HTTP Error 404: Not Found

**Comment by adamg88** [comment]
I'm aware of this, it can be safe ignored for now as it is part of the manual update channel code. It will be rectified in the future.
